### ISSUE TITLE
Total liquidity shows incorrect value

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#650] opened 2020-12-04 04:49 UTC
Every now and than, when visiting the site, the total liquidity figures are off. 

![image](https://user-images.githubusercontent.com/40430285/101123087-aa4aed80-35fc-11eb-94b4-60632f080342.jpeg)

After few refresh, value changes to this
![image](https://user-images.githubusercontent.com/40430285/101123174-e4b48a80-35fc-11eb-96e2-d7d33184f2e9.jpeg)

**Comment by pingustar** [comment] 2020-12-07 10:15
@ashachaf is this a duplicate of https://github.com/bancorprotocol/webapp/issues/657 ?

**Closed** 2020-12-07 10:16 UTC
