### ISSUE TITLE
Input boxes don't allow the user to input numbers beyond the number of digits the UI rounds to

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#51] opened 2020-08-07 12:35 UTC
When you try to input a large number of digits manually (for example when adding liquidity), the app creates a transaction that would revert:

![image](https://user-images.githubusercontent.com/1134236/89645944-86cc9c00-d8c3-11ea-8464-d451bfd9af95.png)

**Comment by Velua** [comment] 2020-08-10 10:29
@pingustar to provide info on replicating.

**Comment by Velua** [comment] 2020-08-17 09:03
Hi @yudilevi  cannot replicate this one atm in staging, can you confirm if it's still happening on your end? If so can we get some number amounts / pool you experienced this with

**Comment by pingustar** [comment] 2020-08-18 07:47
@Velua 

I was able to reproduce this now on Ropsten - Link Pool with amount `0.000000000000007214` LINK

<img width="502" alt="image" src="https://user-images.githubusercontent.com/7262066/90485209-84760780-e137-11ea-9654-182abc103690.png">

<img width="533" alt="Screenshot 2020-08-18 at 09 45 43" src="https://user-images.githubusercontent.com/7262066/90485413-c43cef00-e137-11ea-9b1f-d3e52880f432.png">

**Comment by pingustar** [comment] 2020-08-18 07:49
@Velua 

actually I have to correct my statement. Problem only reproducible on production! So seems to be fixed on staging - just tested and TX went thru without error on staging.

**Closed** 2020-08-19 06:48 UTC
Labels: bug, question
