### ISSUE TITLE
Abnormally high gas fee triggered in Metamask on YFI > BNT swap

### ISSUE THREAD

**Issue by AdamOnChain** [bancorprotocol/webapp#807] opened 2021-01-13 11:24 UTC
After approving YFI to BNT swap the Metamask prompt to confirm swap appeared with a gas fee of $803.

To Reproduce

Try to convert BNT to YFI on bancor.network, approve TX and then try to convert the tokens.

Expected behavior

Prompt to confirm TX with high gas fee appears. 

![image](https://user-images.githubusercontent.com/39331256/104445826-4b38ab00-55a2-11eb-9830-129ff2467417.png)

Additional context

The high gas fee may have appeared after a successful prompt to convert was already confirmed.

**Comment by Velua** [comment] 2021-02-10 12:35
@eratos1122

**Comment by Eratos1122** [comment] 2021-02-11 00:29
![Screen Shot 2021-02-10 at 7 22 29 PM](https://user-images.githubusercontent.com/37297413/107590414-0ec69200-6bd6-11eb-97d8-4f7700af6338.png)
![Screen Shot 2021-02-10 at 7 22 53 PM](https://user-images.githubusercontent.com/37297413/107590426-125a1900-6bd6-11eb-807f-ca2bdfa7e6d0.png)
Hi, @Velua 
The MetaMask error is occurred by the `greaterThanZero` smart-contract method because the `expectedReturn` value is zero
It should be checked on the WebApp first
Would you assign me this issue?
I can fix it and make a PR

**Comment by Velua** [comment] 2021-02-11 05:51
I don't think this is the solution we're looking for, I highly doubt there wasn't an expected return value when the bug was reported. 
Can you reproduce the error should you try replicate a live transaction using the same tokens as the bug reporter?

**Comment by pingustar** [comment] 2021-02-15 13:46
@Eratos1122, I merged your changes that check for input value === zero. Good to have that additional check in place but seems unrelated to the issue the user is experiencing.

@AdamOnChain unless you have tried to swap such a small amount that your return would be 0 TKN - if you can please confirm that that was not the case.

**Comment by Velua** [comment] 2021-04-06 07:09
Cannot replicate, closing as stale.

**Closed by Velua** 2021-04-06 07:09 UTC
Labels: bug
