### ISSUE TITLE
withdraw pool token error - insufficient balance

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1148] opened 2021-03-07 14:46 UTC
**Describe the bug**
as a user, when i try to withdraw my pool tokens, i sometimes get an error indicating i do not have sufficient balance
![image](https://user-images.githubusercontent.com/40430285/110243764-6c939300-7f64-11eb-9955-4068d31b9307.png)

**To Reproduce**
i am unable to reproduce.
please indicate the process in the code that identify the pool token balance and the calculation when i select 100% to identify where this error might occur.

**Comment by Velua** [comment] 2021-03-08 05:13
@pingustar Can you take a look at this one? I'm confused looking at ```PoolActionsRemoveV1.vue``` it seems to have too many variables.

**Comment by pingustar** [comment] 2021-03-08 18:37
The error is a 'leftover' from the previous design. I have removed it now... as we don't need it anymore.  The only user input (percentage slider) is limited to 100% max.

We can close this issue with the fix in the following PR.

@Velua no further action required, just FYI: I think the error is caused by a tiny difference in the results of these two methods which should return the same value.

```
const results = await vxm.bancor.calculateOpposingWithdraw({
        id: this.pool.id,
        reserves: [
          { id: this.pool.reserves[0].id, amount: amount.toString() },
          { id: this.pool.reserves[1].id, amount: "" }
        ],
        changedReserveId: this.pool.reserves[0].id
      });
      const opposingAmount = results.opposingAmount;
```

```
const res = await vxm.bancor.getUserBalances(this.pool.id);
const balance2 = res.maxWithdrawals[1].amount
```

**Closed** 2021-03-09 01:09 UTC
Labels: bug
