### ISSUE TITLE
App loads into a bare mode

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#89] opened 2020-08-14 12:07 UTC
I noticed that multiple times when I open the app, this is what I see -
![image](https://user-images.githubusercontent.com/1134236/90247683-c9e8bb00-de3f-11ea-806f-bb3a14673732.png)

Refresh usually fixes the problem.

**Comment by Velua** [comment] 2020-09-14 10:03
@yudilevi How's your experience with this been lately?

**Comment by yudilevi** [comment] 2020-09-14 10:44
@Velua happened again a few days ago

**Comment by ashachaf** [comment] 2020-10-25 07:10
@Velua - 
1. can you reproduce?
2. do you have a direction on what is wrong?

let me know if we can solve or close this task.

**Comment by Velua** [comment] 2020-10-25 07:28
Not a lot, haven't been able to reproduce.

**Comment by Velua** [comment] 2020-10-26 06:20
@ashachaf or @yudilevi have you seen this lately?

**Comment by yudilevi** [comment] 2020-10-26 08:44
Nope but it usually happens to new users, potentially with poor connection.

**Comment by ashachaf** [comment] 2020-10-26 11:19
it is related to performance.
this was addressed in. different stories.
if cannot reproduce, i would close it and open again if needed.

**Closed by ashachaf** 2020-10-26 11:19 UTC
Labels: Performance issues, bug
