### ISSUE TITLE
Funky tooltip behaviour

### ISSUE THREAD

**Issue by Velua** [bancorprotocol/webapp#497] opened 2020-11-10 00:58 UTC
In this video - https://streamable.com/51q0y1

We can see that when I mouse over the tooltip for the other item comes up instead, I've seen this happen when there isn't a unique key set per tooltip component.

**Comment by pingustar** [comment] 2020-11-10 09:26
This is most likley because the table is restricting the space to display the tooltips. I had a similar problems on another project with dropdowns inside a table.

Looking into it.

**Comment by pingustar** [comment] 2020-11-17 13:01
Only solution I was able to find is adding a `minHeight` to the table. Not the best but will fix this issue.

What do you think about that @Velua ?

**Comment by Velua** [comment] 2020-11-18 04:01
Is this really the issue then? 
It's definitely not occurring due to a duplicate ID being used for the tooltip or anything?

**Comment by pingustar** [comment] 2020-11-18 07:41
Yes I am pretty sure about it.

`:id="'popover-cliff-' + item.id"` is how the ID is set. And the funky behaviour seems to only happens if there are just a few positions in the table. I'll test this out and we'll see.

I'll ping you for review.

**Comment by pingustar** [comment] 2020-11-24 15:36
fixed by adding min-height and display block css to the table.

**Comment by pingustar** [comment] 2020-11-30 11:53
reopening this as I just noticed that the implemented fix messes with the table

![image](https://user-images.githubusercontent.com/7262066/100607308-12eb4f00-330b-11eb-8bac-f7bc973dbdba.png)

**Comment by ashachaf** [comment] 2021-01-14 21:36
@pingustar 
i am unable to reproduce. please close if not needed.

**Closed** 2021-01-26 18:06 UTC
Labels: bug
