### ISSUE TITLE
insufficient funds error message not showing

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#159] opened 2020-09-13 07:47 UTC
go to "add liquidity" (v1 pool, i've tested bnt/usdt)
enter the amount in the token row (usdt in this case).
notice that even if you do not have sufficient balance on token or bnt, there is no error message.

![image](https://user-images.githubusercontent.com/40430285/93013135-535deb00-f5ae-11ea-880e-4872fb382886.png)

**Comment by pingustar** [comment] 2020-09-13 20:14
![image](https://user-images.githubusercontent.com/7262066/93027608-58528700-f60e-11ea-9f36-ac669d151e24.png)


cannot reproduce this. @ashachaf are you still experiencing this? @Velua are you able to reproduce this?

**Comment by Velua** [comment] 2020-09-14 10:49
@pingustar Yeah looks like it's happening on the second text field https://streamable.com/h5h07o

**Comment by pingustar** [comment] 2020-09-14 15:02
fixed with commit https://github.com/bancorprotocol/webapp/commit/abaefa3986993ceb471df285b93a777729fa3e6d and on staging for review.

**Closed by pingustar** 2020-09-14 15:02 UTC
Labels: bug
