### ISSUE TITLE
Governance UI fixes

### ISSUE THREAD

**Issue by katyarozenfeld** [bancorprotocol/webapp#268] opened 2020-10-11 08:00 UTC
Hi @H34D , here are a few small UI fixes that aren't flow related and not urgent, but should be added at some point:

**Create a Proposal** (screenshot attached)

- [x] 1. Please change warning message design
- [x] 2. Please change Title and Description design  - grey box with dark text.
- [x] 3.  Title and Description box isn’t scrollable - I can’t read whole description

**Proposals table** (screenshot attached)

- [x] 1.  Please align date & time in proposal details to be "columns" as it is Zeplin

Thank you!

<img width="873" alt="Screenshot at Oct 11 10-56-36" src="https://user-images.githubusercontent.com/69288176/95673406-d889ef00-0bb0-11eb-834c-e594f602aafd.png">
<img width="1221" alt="Screenshot at Oct 11 10-50-46" src="https://user-images.githubusercontent.com/69288176/95673407-dc1d7600-0bb0-11eb-8fa6-c6b091ab7895.png">

**Comment by H34D** [comment] 2020-11-05 11:32
> * [ ]  There is a small bug - grey box doesn't reach the edge of the table

that is a duplicate of #334

**Comment by H34D** [comment] 2020-11-05 11:38
> * originally in design the positions were supposed to be expandable and not scrollable table. Is this a mistake or it's something that was decided to be?

that is a duplicate of #285

**Comment by H34D** [comment] 2020-11-05 14:17
fixed

**Closed by H34D** 2020-11-05 14:17 UTC
Labels: UI/UX
