### ISSUE TITLE
swap calculation/slippage indication issue

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#1098] opened 2021-02-25 12:47 UTC
when testing the swap, we have noticed strange slippage indication on these two cases.
first case:
ceek->eth which shows 99% slippage
![image](https://user-images.githubusercontent.com/40430285/109155473-41e15780-7778-11eb-896b-bf3b0bbbf2d3.png)

2nd case:
ceek->bnt which shows almost no slippage.
both cases use the same amount of ceek tokens.
![image](https://user-images.githubusercontent.com/40430285/109155482-44dc4800-7778-11eb-8686-c7cdf8e2ec39.png)

**Comment by Velua** [comment] 2021-02-26 06:18
This is due to a pathing issue, I've created a PR now.

**Comment by pingustar** [comment] 2021-03-15 16:08
@Velua I have been tracking down a bug in the swap feature. My investigation leads me to the `findBestPath` vuex action. After talking with Yudi, we think that the issue is caused by a path that uses USDB.

How to reproduce:
1. Go to Swap
2. Select USDT as sell token
3. Select any token but BNT as buy token
=> rate calculation fails and loading animation never stops

As a test I have manually set `checkMultiplePaths` inside `findBestPath` to `false` and that seems to fix the above issue. 

As I lack the knowhow of these mechanics and the path finding ... I would like to hand this over to you.

**Comment by Velua** [comment] 2021-03-22 04:37
This should be fixed now, does it look okay to you now @pingustar ?

**Comment by pingustar** [comment] 2021-03-22 12:47
LGTM

**Closed by pingustar** 2021-03-22 12:47 UTC
Labels: bug, priority
