### ISSUE TITLE
getting pool roi failed! Error: Returned error: execution reverted: ERR_INVALID_RATE

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#562] opened 2020-11-17 16:05 UTC
on production +mainnet i get lots of these errors.

![image](https://user-images.githubusercontent.com/40430285/99414278-54d5c780-28ff-11eb-8359-18f486ec04a8.png)

**Comment by pingustar** [comment] 2020-11-18 08:38
duplicate of #555

**Closed by pingustar** 2020-11-18 08:38 UTC
Labels: bug
