### ISSUE TITLE
protected table - error calculating columns data

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#602] opened 2020-11-25 11:52 UTC
occasionally, usually happens after the site is open for some time, we start getting error messages which cause calculations to fail.

![image](https://user-images.githubusercontent.com/40430285/100224320-59186b00-2f25-11eb-9606-65e7ddb20a31.png)

**Comment by pingustar** [comment] 2020-11-25 13:15
Isnt this a duplicate of https://github.com/bancorprotocol/webapp/issues/555

@ashachaf @yudilevi has the contract been fixed? Is there any action required from our end? https://github.com/bancorprotocol/webapp/issues/555#issuecomment-728323986

**Closed by pingustar** 2020-11-25 13:15 UTC
Labels: bug, priority
