### ISSUE TITLE
Insufficient balance for convert error when the user has enough balance

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#76] opened 2020-08-11 14:11 UTC
![image](https://user-images.githubusercontent.com/1134236/89907687-a5999e00-dbf5-11ea-96d0-9445202034ae.png)

**Comment by pingustar** [comment] 2020-08-12 13:19
cannot reproduce. Is this a multi users issue? 

Closing for now.

**Comment by ashachaf** [comment] 2020-08-13 09:58
go to swap
select token full balance to swap
click confirm
trigger the metamask transaction window (do not sign it)
go back to swap
try to enter any amount of the toToken from the previous steps

**Comment by ashachaf** [comment] 2020-08-13 11:53
tested on ropsten as well:
swap eth to any token
enter increasing amounts in the eth input field.

https://streamable.com/uohrpp

**Comment by Velua** [comment] 2020-08-13 21:59
@pingustar to investigate, otherwise escalate this one to me.

**Comment by yudilevi** [comment] 2020-08-14 09:10
More info from the user
![image](https://user-images.githubusercontent.com/1134236/90233615-15429f80-de27-11ea-8ce6-d8c8579f8ed7.png)

**Comment by yudilevi** [comment] 2020-08-14 09:36
and from another user -
![image](https://user-images.githubusercontent.com/1134236/90235902-b5e68e80-de2a-11ea-9bbe-0918bb079dd5.png)

**Closed** 2020-08-14 13:22 UTC
Labels: bug, priority
