### ISSUE TITLE
Transaction confirmation screen gets stuck occasionally

### ISSUE THREAD

**Issue by yudilevi** [bancorprotocol/webapp#106] opened 2020-08-18 15:29 UTC
Users are reporting the popup staying up even though transactions are already confirmed for a while on chain.

![image](https://user-images.githubusercontent.com/1134236/90533147-c37c7b00-e180-11ea-8aec-7c8d332f4440.png)

**Comment by Velua** [comment] 2020-08-20 06:36
@yudilevi Haven't seen this one, do we know what app this user is running? Can try it out to see if there's any compatibility issues.

**Comment by yudilevi** [comment] 2020-08-20 10:23
Hard to get more info now but it also happened during high gas prices and long waiting times, might be related.

**Comment by pingustar** [comment] 2020-08-31 10:24
cannot reproduce. Closing for now. Please reopen if issue comes up again.

**Closed by pingustar** 2020-08-31 10:24 UTC
Labels: bug
