### ISSUE TITLE
Protection table - "Fully Protected Value" showing "NaN"

### ISSUE THREAD

**Issue by nhindman23** [bancorprotocol/webapp#348] opened 2020-10-19 07:25 UTC
![image](https://user-images.githubusercontent.com/53524917/96414078-4a87b700-11f5-11eb-93a3-65cecfab74c0.png)

**Comment by Velua** [comment] 2020-10-21 09:11
@yudilevi who can we reach out too to check this out? Unable to replicate

**Comment by Velua** [comment] 2020-10-21 09:11
@ashachaf do you see this or zeros on your end?

**Comment by ashachaf** [comment] 2020-10-26 12:50
closing for now as we are unable to reproduce.
also, might be related to performance.

**Closed by ashachaf** 2020-10-26 12:50 UTC
Labels: bug, priority
