### ISSUE TITLE
incorrect error when trying to add liquidity

### ISSUE THREAD

**Issue by ashachaf** [bancorprotocol/webapp#68] opened 2020-08-10 08:31 UTC
there is some inconsistency when trying to add funds to bancor v2 pool.

same user, 
when trying to add 200, error (correctly) "insufficient balance"
when trying to add 1468, no error (while balance is 159) 
when trying to add 1500, error (correctly), "pool cap. reached"
![image](https://user-images.githubusercontent.com/40430285/89764162-95ea5e80-dafc-11ea-9263-983b5976b471.png)
![image](https://user-images.githubusercontent.com/40430285/89764179-9edb3000-dafc-11ea-92cf-0d2613100828.png)
![image](https://user-images.githubusercontent.com/40430285/89764378-f2e61480-dafc-11ea-8a78-62ebeaf8b793.png)

**Comment by Velua** [comment] 2020-08-10 10:13
Me and @pingustar currently unable to replicate the issue in the 2nd screen shot, can we get a confirmation this is still present and steps on reproducing?

**Comment by yudilevi** [comment] 2020-08-10 10:31
@Velua it was reported earlier today so I assume it's still relevant

**Comment by Velua** [comment] 2020-08-10 10:36
Swap has had an update in the past hour containing several days worth of work @yudilevi

**Comment by yudilevi** [comment] 2020-08-10 10:54
@Velua anything that should have fixed this issue?

**Comment by Velua** [comment] 2020-08-10 11:14
Yeah

**Comment by yudilevi** [comment] 2020-08-10 11:33
@Velua I'm asking about something in particular - I don't like things that are getting "magically" fixed without knowing the reason - they can pop up back again after a while.

**Comment by Velua** [comment] 2020-08-10 12:14
I just know we have made and still making changes around this area, it's too hard to tell if it's fixed or not when we weren't able to replicate this problem in the first place.

**Comment by pingustar** [comment] 2020-08-11 13:45
Cannot reproduce this bug. 
Will send this to review.
If you can reproduce please reopen.

**Comment by ashachaf** [comment] 2020-08-13 10:04
go to pool
bnt/link v2 pool
try to add liquidity to link token.
try to add more than your current balance:
![image](https://user-images.githubusercontent.com/40430285/90122006-5f634c80-dd65-11ea-9227-0de4792a6d1e.png)

try to add 50000
![image](https://user-images.githubusercontent.com/40430285/90122056-6b4f0e80-dd65-11ea-95cc-003db669f364.png)

copy the amount from the error message and try adding it
![Uploading image.png…]()

**Comment by Velua** [comment] 2020-08-19 06:40
@ashachaf Just tried this out and seems to be working, can we confirm this is still happening?

**Comment by ashachaf** [comment] 2020-08-19 07:42
seems to be working now.
i cannot reproduce.

**Closed** 2020-08-19 16:08 UTC
Labels: question
